### ISSUE TITLE
Refresh expiration of cookie

### ISSUE THREAD

**Issue by artherd42** [sapcc/maia#69] opened 2021-12-09 14:06 UTC
TEST CASE:
1. Login to https://maia.x.x.x/[domain_name]/graph?domain_id=y with basic authentication
2. Wait at least 8 hours
3. repeat step 1

EXPECTED BEHAVIOUR:
User is logged in.

OBSERVED BEHAVIOUR:
Login fails.
Error log message: Request with wrong credentials from XYZ: Authentication failed

Maia is using existing cookie for authentication even when the cookie has already expired. 
Workaround is to delete the cookie manually. But Maia should re-authenticate and refresh the cookie.

**Comment by notque** [comment] 2021-12-09 23:55
Okay, I'm trying to replicate, it looks like it's handling it properly but perhaps after 8 hours it will make sense.

**Comment by artherd42** [comment] 2021-12-10 07:49
Cookie details:
![image](https://user-images.githubusercontent.com/4355027/145536554-1e74b555-a6b0-4c1f-a38f-e207ee5773e5.png)

Tested with Chrome Version 96.0.4664.93. I would expect, the browser deletes expired cookies, but apparently it doesn't. 
Mitigation: Either browser setting **Clear cookies and site data when you close all windows** or manually delete the Maia cookie.

**Comment by notque** [comment] 2021-12-10 19:57
Replicated and confirmed. 

`2021/12/10 12:20:13 ERROR: Authorization header missing (no username/password or token)
2021/12/10 12:45:47 ERROR: Authorization header missing (no username/password or token)
2021/12/10 19:54:42 INFO: Request with wrong credentials from : Resource not found`

**Comment by notque** [comment] 2021-12-10 19:59
I'm not sure what we can do otherwise, your mitigation is correct. Should we close the ticket?

**Comment by notque** [comment] 2022-03-18 18:22
Closing ticket due to acceptable mitigation based around browser.

**Closed by notque** 2022-03-18 18:22 UTC
Labels: bug
